react-hot-loader: Disable safetyNet to work with ESM
After upgrading webpack and plugins/loaders, there was an error from
react-hot-loader:

    ReferenceError: module is not defined

A known workaround is to enable safetyNet [1] so the code referencing
`module` is not executed.

I'm not sure why this was not shown before the webpack upgrades, but
don't feel like digging deeper to find out.

[1]: https://github.com/gaearon/react-hot-loader/issues/1102#issuecomment-459570955