Use markdown heading for changelog
The YAML frontmatter was used for an old way of hosting the docs¹.

When used with the current docs hosting setup², this syntax results in a
Sphinx build "error" (it is rendered with as "title: Changelog"):

    ERROR: Document or section may not begin with a transition.

Using a markdown heading removes the error and allows for intended
styling.

¹ https://nextstrain.github.io/auspice/
² https://docs.nextstrain.org/projects/auspice/en/stable/releases/changelog.html