Replace `lodash.pick` for proper type assignment
Use of `lodash.pick` causes type error
```
src/actions/measurements.ts(211,3): error TS2322: Type 'Partial<ControlsState>' is not assignable to type 'MeasurementsControlState'.
  Property 'measurementsGroupBy' is optional in type 'Partial<ControlsState>' but required in type 'MeasurementsControlState'.
```

Instead of using type casting, just replace `lodash.pick` for the
proper type assignment.